spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/message_service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Configure timezone to UTC
        jdbc:
          time_zone: UTC
  application:
    name: message-service
  # Set default timezone to UTC
  jackson:
    time-zone: UTC

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 