spring:
  datasource:
    url: postgresql://moomin_plus_plus_database_user:lHwDxVOlEQUSXG87Qnquoewmb7aGI1NF@dpg-d24ptvqdbo4c73a0ef10-a.frankfurt-postgres.render.com/moomin_plus_plus_database
    username: moomin_plus_plus_database_user
    password: lHwDxVOlEQUSXG87Qnquoewmb7aGI1NF
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: message-service

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 